# -*- coding: utf-8 -*-
"""lambda_function.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUs8V95OZqgYB2iz_Bpz4yjeVHJExmyQ
"""

import json
import boto3
import requests
import pandas as pd
from datetime import datetime
from io import StringIO

def lambda_handler(event, context):
    cities = ['Warsaw', 'Krakow', 'Wroclaw', 'Gdansk']
    API_KEY = '05ba2f27f743430ac9f611f7ef4efae1'

    weather_data = []

    for city in cities:
        url = f'https://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric'
        r = requests.get(url)
        res = r.json()
        weather_data.append({
            'city': city,
            'temp': res['main']['temp'],
            'humidity': res['main']['humidity'],
            'weather': res['weather'][0]['description'],
            'timestamp': datetime.utcnow().isoformat()
        })

    df = pd.DataFrame(weather_data)

    # Save to CSV in memory
    csv_buffer = StringIO()
    df.to_csv(csv_buffer, index=False)

    # Upload to S3
    s3 = boto3.client('s3')
    now = datetime.utcnow().strftime('%Y-%m-%d_%H-%M-%S')
    s3.put_object(Bucket='your-s3-bucket-name',
                  Key=f'weather/raw/weather_data_{now}.csv',
                  Body=csv_buffer.getvalue())

    return {
        'statusCode': 200,
        'body': json.dumps('Data fetched and uploaded successfully!')
    }